DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS TRANSFERS;

CREATE TABLE ACCOUNTS (
    ID BIGINT PRIMARY KEY,
    FIRST_NAME VARCHAR (50) NOT NULL,
    LAST_NAME VARCHAR (50) NOT NULL,
    BALANCE DOUBLE PRECISION NOT NULL
);

CREATE TABLE TRANSFERS (
    ID BIGINT PRIMARY KEY,
    AMOUNT DOUBLE PRECISION NOT NULL,
    SOURCE_ID NUMBER REFERENCES ACCOUNTS(ID),
    TARGET_ID NUMBER REFERENCES ACCOUNTS(ID),
    TRANSFER_TIME DATE
);

ALTER TABLE TRANSFERS
    ADD FOREIGN KEY (SOURCE_ID)
    REFERENCES ACCOUNTS(ID);

ALTER TABLE TRANSFERS
    ADD FOREIGN KEY (TARGET_ID)
    REFERENCES ACCOUNTS(ID);
