SELECT GROUPED.* FROM
(
  SELECT  ACTUAL.SOURCE_ID, SUM(ACTUAL.AMOUNT) AS GROUP_SUM FROM
    (SELECT * FROM ACCOUNTS A RIGHT JOIN TRANSFERS T ON A.ID = T.SOURCE_ID WHERE T.TRANSFER_TIME > '2019-12-15') AS ACTUAL
  GROUP BY ACTUAL.SOURCE_ID
) AS GROUPED
WHERE GROUPED.GROUP_SUM > 1000;
